### PR TITLE
Fixed Issues 126 and 127 (Culpa links and BC call number links)

### LINKED ISSUE #126: remove middle initials for CULPA searches
CULPA doesn't track middle initials, so including them makes CULPA search fail (this is a problem with CULPA, but probably won't be fixed soon).

Get rid of middle initials for CULPA search links.

### LINKED ISSUE #127: Call number links do not work for Barnard courses
Because they all go to a Columbia.edu domain.

### PR DESCRIPTION
**Pull request by G-ram**
Fixes #126 
Fixes #127

### CODE REVIEW

**Comment by brishin** [comment]
Hey, check out the changes that I made to your commit message so that it fits [this syntax](https://help.github.com/articles/closing-issues-via-commit-messages).

**Comment by brishin** [comment]
Sorry, not seeing how this fixes #127. Could you explain?

**Comment by G-ram** [comment]
Yeah, so the issue was not that it was not going to barnard.edu, but rather that it was going to the wrong link in the CU directory. Barnard courses are part of the CU directory, the difference is that they begin with BC. The links however were pointing to a url with X in them rather than a BC. I fixed that.

**Comment by brishin** [comment]
Ah, makes sense.

**Pull request merged**
