### PR TITLE
update placeholder again

### PR DESCRIPTION
**Pull request by schlosser**
Search by professor feature got removed, but the the placeholder stayed

### CODE REVIEW

**Comment by brishin** [comment]
screen shot 2014-04-11 at 12 58 02
hmm?

**Comment by brishin** [comment]
The main search box is looking at all the fields of a document and the sub search boxes are specifically looking at certain fields.

**Comment by schlosser** [comment]
had globalcore checked.....

**Comment by schlosser** [comment]
So can you filter by anything else?

**Comment by brishin** [comment]
Yep! https://github.com/adicu/Courses/blob/master/src/js/models/Course.coffee#L133-L141
What fields are you thinking of? (Time might be hard as of now).

**Pull request closed without merging**
