### PR TITLE
add new logo and twitter, facebook, and google meta tags

### LINKED ISSUE #190: Make sure google can index us

### PR DESCRIPTION
**Pull request by schlosser**
Should improve our appearance on Facebook and Twitter, and allow indexing on Google  closes #190

### CODE REVIEW

**Comment by natebrennand** [comment]
diff pictures?

**Comment by schlosser** [comment]
We won't know if anything works unless it's live.

**Comment by natebrennand** [comment]
even the picture?

**Comment by schlosser** [comment]
Thought we had to test in prod, then ngrok to the rescue

screen shot 2014-07-30 at 12 26 29 am
screen shot 2014-07-30 at 12 28 53 am

**Comment by natebrennand** [comment]
awesome, lgtm
:+1:

**Comment by brishin** [comment]
👍 lgtm

**Comment by brishin** [comment]
I'm not sure this should be the final logo, but sounds good for now.

**Comment by schlosser** [comment]
definitely temp

**Pull request merged**
