### PR TITLE
Better description

### PR DESCRIPTION
**Pull request by rbtying**
More useful information -- courses is pretty worthless w/o call numbers

### CODE REVIEW

**Comment by brishin** [comment]
Great idea, only problem is resizing the popover when there are too many sections ie CC or Lit Hum

**Comment by rbtying** [comment]
Right now it scrolls b/c I was too lazy to work out bootstrap popover 
resizing. Min-height / variable height would probably work.

-- Robert Ying

**Comment by brishin** [comment]
I remember having tons of trouble with the popover CSS. If you could take a look, that'd be awesome.

**Comment by brishin** [comment]
But looks good.

**Pull request merged**
