### PR TITLE
Remove child checking to greatly reduce number of "this course has no av...

### PR DESCRIPTION
**Pull request by brishin**
...ailable sections" dialogs.

Re: branches on origin - turns out my brishin remote is actually pointing to origin. Will fix.

### CODE REVIEW

**Comment by brishin** [comment]
@natebrennand bump

**Comment by natebrennand** [comment]
I think we should have an alert or something to convey what's happening. It seems buggy when the course gets added but doesn't show up on the week view

**Comment by brishin** [comment]
Got it. Which courses does this happen for?

**Comment by natebrennand** [comment]
"Masterpieces of Western Art"
they haven't given us any times for it yet, they aren't on the directory yet either...

**Pull request closed without merging**
